version: 2.1
orbs: 
  commitlint: conventional-changelog/commitlint@1.0.0

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
         name: Build
         command: mvn -B -DskipTests clean package
      - run:
          name: Analyze on SonarCloud

          command: mvn verify sonar:sonar -Dsonar.projectKey=ISA-Organization_ISA-Projekat -DskipTests

workflows:
  main:
    jobs:
      - commitlint/lint
      - build:
          context: SonarCloud